# -*- coding: utf-8 -*-
"""CIE-2  LAB EXAM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O82x_9hMh1amYuaGBkh36Krkfs2XL281
"""

import pandas as pd
import numpy as np
import seaborn as sns
df=pd.read_csv('/content/titanic.csv')
df

df.info()

df.describe()

df['Pclass'].unique()

df[['Fare','Age']].mean()

df[['Fare','Age']].median()

df['Age'].mode()

df.isnull()

df

sns.countplot(data=df,x='Survived',hue='Pclass')
df['Survived'].replace({0:'non-survived',1:'Survived'},inplace=True)

df['Survived']

df['Survived'].replace({0:1,1:0},inplace=True)
df

df['Age'].fillna(df['Age'].mean(),inplace=True)
df

mode=df[['Age','Fare']].mode()
mode
mean=df[['Age','Fare']].mean()
mean
median=df[['Age','Fare']].median()
median

sns.heatmap(df.isnull())

import numpy as np
import scipy . stats as stats

df['Age'] = stats.zscore(df['Age'])
threshold = 2

ans= df[df['Age']>threshold]
sns.boxplot(x='Age',data=df)