# -*- coding: utf-8 -*-
"""NEW CIE-1 IRANNA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/131G5l6x8q8lkxnI9ivzt14cNkRTf-YqP
"""

import pandas as pd

Series_A = pd.Series([1, 2, 3, 4, 5])
Series_B = pd.Series([2, 4, 6, 8, 10])

common_items = Series_A[Series_A.isin(Series_B)]

print(common_items)

# 1. Histogram and frequency mpg
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/mtcars.csv')

plt.figure(figsize=(8, 6))
plt.hist(data['mpg'], bins=10, edgecolor='k', color='lightgreen')
plt.xlabel('MPG')
plt.ylabel('Frequency')

plt.show()

# 2. Scatter plot  weight of the car and mpg

plt.figure(figsize=(8, 6))
plt.scatter(data['wt'], data['mpg'], color='black', marker='o')
plt.xlabel('Car Weight')
plt.ylabel('MPG')

plt.show()

# 3. Bar plot frequency distribution of transmission

transmission_counts = data['am'].value_counts()
plt.figure(figsize=(8, 6))
transmission_counts.plot(kind='bar', color='pink')
plt.xlabel('Transmission ')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.show()

# 4. Box and Whisker plot of mpg

plt.figure(figsize=(8, 8))
plt.boxplot(data['mpg'], vert=False, notch=True, patch_artist=True, boxprops=dict(facecolor='blue'))
plt.xlabel('MPG')

plt.show()